// SPDX-FileCopyrightText: 2026 Contributors to ddc-ci-daemons <https://github.com/digitaltrails/ddc-ci-daemons>
// SPDX-License-Identifier: GPL-2.0-or-later

///! DDC CI D-Bus service

mod ddc_ci_dbus_service;

use std::env::VarError;
use log::{error, info};
use zbus::blocking::{connection};
use ddc_ci_dbus_service::DdcCiDbusService;
use ddcutil_backend::ddcutil::{extract_edid_base64, start_watch_displays, InternalEventKind};
use crate::ddc_ci_dbus_service::DdcCiDbusDisplayEventType;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    env_logger::init();

    // Create our implementation of the service and obtain the receiver channel
    let (service, internal_event_receiver) = DdcCiDbusService::new();

    if is_env_enabled("DDC_CI_WATCH_DISPLAYS", true) {
        match start_watch_displays() {
            Ok(()) => info!("Enabled libddcutil watch_displays."),
            Err(e) => error!("Failed to enable libddcutil watch_displays, continuing anyway: {:?}", e),
        }
    }

    if is_env_enabled("DDC_CI_POLL_DISPLAYS", true) {
        service.start_polling();
    }

    // Blocking builder to bind and serve the interface
    let connection = connection::Builder::session()?
        .name(DdcCiDbusService::SERVICE_NAME)?
        .serve_at(DdcCiDbusService::OBJECT_PATH, service)?
        .build()?;

    let object_server = connection.object_server();

    let interface_name = <DdcCiDbusService as zbus::object_server::Interface>::name();
    info!("Running D-Bus Service: {}; Object: {}; Interface: {}",
        DdcCiDbusService::SERVICE_NAME,
        DdcCiDbusService::OBJECT_PATH,
        interface_name);

    let interface_ref = object_server
        .interface::<_, DdcCiDbusService>(DdcCiDbusService::OBJECT_PATH)?;

    let signal_emitter = interface_ref.signal_emitter();


    info!("Service initialized. Processing background events...");

    // Process libddcutil watch events into signals. This only handles libddcutil watch events,
    // DPMS and vcp changes are handled elsewhere because the service detects them itself, they
    // are not generated by libddcutil.  The work internal here, means internal to this service,
    // not sent directly out to clients.
    while let Ok(event) = internal_event_receiver.recv() {
        let edid_base64 = extract_edid_base64(&event);
        let event_type = if edid_base64.is_empty() {
            DdcCiDbusDisplayEventType::DisplayDisconnected as i32
        } else {
            DdcCiDbusDisplayEventType::DisplayConnected as i32
        };
        info!("Internal display change event detected. Broadcasting signal event_type={} edid_base64={}",
            event_type, edid_base64);
        if let Err(e) = zbus::block_on(DdcCiDbusService::connected_displays_changed(
            signal_emitter,
            &edid_base64,
            event_type,
            0,
        )) {
            log::error!("Failed to broadcast display change event over bus: {}", e);
        }
    }
    // Must be shutting down the service.
    Ok(())
}

fn is_env_enabled(env_variable_name: &str, default_value: bool) -> bool {
    let value = std::env::var(env_variable_name)
        .map(|v| ["yes", "1", "true", "on"].iter().any(|s| v.eq_ignore_ascii_case(s)))
        .unwrap_or(default_value);
    info!("Environment variable: {}={} (default={})", env_variable_name, value, default_value);
    value
}


